### ISSUE TITLE
Consider using navigator.sendBeacon()?

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/ping-centre#17]
@6a68 mentioned about there is a built-in utility function [navigator.sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) available.

I think it's worth investigating that if it's suitable for Ping-centre. Note that this is a web api other the addon SDK, that means we could use it directly on the content side as well as the addon side through the hidden window.

**Comment by emtwo** [comment]
We can use `sendBeacon()` as a default and fall back to plain `fetch` if we don't have access to `navigator`

**Comment by 6a68** [comment]
It [turns out](https://github.com/mozilla/testpilot-metrics/issues/25) that the `sendBeacon` API can be preffed off, and might be preffed off by addons like Privacy Badger. In this case, there simply won't be a `sendBeacon` defined on `navigator`, so "'sendBeacon' in navigator" is an adequate feature check.

In contrast, `fetch` can't be preffed off, but it also doesn't wait for the networking stack to be idle before firing a ping.

SDK or bootstrapped addons should always be able to get access via `Services.appShell.hiddenDOMWindow.navigator`, as mentioned in the bug description.
