### ISSUE TITLE
Alternative choices for joi

### ISSUE THREAD

**Issue by k88hudson** [mozilla/ping-centre#35]
Since joi isn't really designed to work in the browser (see issue 528 on the joi issue tracker, for example), here are some possible alternatives. They vary quite a bit in terms of power so it depends on what you need.

I did a quick test for build sizes are with webpack, with production optimizations on:

```
joi-browser           162kb
yup                    77kb
js-schema              16kb
react-schema         5.49kb
```

**Comment by 6a68** [comment]
refs #26

**Comment by 6a68** [comment]
@emtwo Hey, did you have a particular replacement in mind?

I tried replacing joi with joi-browser, then got stung by its use of the `config` npm package, which uses conditional requires, [causing webpack+es6 to barf](https://github.com/lorenwest/node-config/issues/345).

If you'd like to stick with joi-browser, I can find some webpack hack around those conditional requires (and open a PR to change libraries), otherwise I'm happy to write a patch to move to a different library.

**Comment by emtwo** [comment]
@6a68 I haven't taken a look at this yet, I was going to get around to it probably Monday. I was hoping to use joi-browser. If you happen to know an exact approach or library that would be best to use, you're welcome to make a PR or let me know what you've found so far and I can do it.

I just don't want to take up your time to patch ping-centre when it should be a module to help make your life easier!

Let me know what you think!

**Comment by 6a68** [comment]
@emtwo o hai :-)

I was wrong earlier - it's ping-centre that's using `config`, not `joi-browser`. I'll file a separate bug for that issue. I'm not a huge webpack user, so maybe there's a really easy solution I'm missing.

**Comment by emtwo** [comment]
I'm not a huge webpack user either but luckily I've got @k88hudson's help! I'll try to sort out these nuisances as soon as I can :)

**Comment by pdehaan** [comment]
It's a bit more verbose than Joi, but I quite like [**ajv**](https://github.com/epoberezkin/ajv):

> _The fastest JSON Schema validator for node.js and browser. Supports v5 proposals._
